name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Download Test Data
      run: |
        wget -O TestBags.zip https://www.dropbox.com/sh/iprwyiwlud7ujv0/AADZbauYvWnMsqRDKaCZPyODa?dl=1
        mkdir Sources/RosBagConverterTests/TestBags/
        unzip TestBags.zip -d Sources/RosBagConverterTests/TestBags
    - name: Test
      run: dotnet test --no-restore --verbosity normal
